---
- hosts: all
  become: yes
  tasks:
    - name: Criação de Grupos de Usuários
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - g_ti
        - g_diretoria
        - g_suporte
    - name: Adicionando Usuário Suporte
      user:
        name: suporte
        comment: Suporte TI
        uid: 2000
        shell: /bin/bash
        group: g_ti
        groups: g_diretoria,g_suporte
        password: '$6$vyBZEp67$Yhsi.ogMxR3fiEQgejE6dxFd6AWN.pSLnmgzoVhl.Am2lVpD9YV4IpHDjr6MwcMhmLVFPE4Z8MjM.hKfWHNTc1'
        update_password: on_create
        append: yes

